services:
  postgres:
    image: postgres:16.9-alpine3.22
    pull_policy: always
    environment:
      - POSTGRES_PASSWORD=root1234
      - POSTGRES_USER=root
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
  keycloak:
    image: quay.io/keycloak/keycloak:26.4.0
    pull_policy: always
    ports:
      - '8083:8080'
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=root1234
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KEYCLOAK_FEATURES=scripts
    volumes:
      - './init/bookstore-realm.json:/opt/keycloak/data/import/bookstore-realm.json'
    command:
      - start-dev
      - --import-realm
    depends_on:
      - postgres